Makefile
powerfulseal/policy/ps-schema.json
powerfulseal/policy/scenario.py
setup.py
tests/policy/example_config.yml
tests/policy/test_scenario.py

Modifies the schema, the interpreter and the tests to account for the change.
Closes https://github.com/bloomberg/powerfulseal/issues/15

Support `ratio` in `randomSample`, instead of `percentage`

---

powerfulseal/cli/pscmd.py

Probably best to use the right name.

Fix `kubectl` command in the interactive shell

---

powerfulseal/cli/__main__.py
powerfulseal/execute/remote_executor.py

For certain commands in interactive mode, the powerful seal connects to the host via ssh. If the host is not present in your `known_hosts`, the seal will fail to connect and throw an error of the form:
```
Executing '['sh', '-c', 'sudo docker ']' on sk1-worker-1
--------------------------------------------------------------------------------
xxx.xxx.xxx.xxx
Error creating SSH connection
Original error: Server 'xxx.xxx.xxx.xxx' not found in known_hosts
```
This PR takes an optional command line flag that allows ssh to connect to hosts whose keys are not found in known_hosts
closes #22

Ssh allow missing host keys

---

.gitignore
.travis.yml
Makefile
README.md
TESTING.md
powerfulseal/cli/__main__.py
powerfulseal/cli/pscmd.py
powerfulseal/clouddrivers/driver.py
powerfulseal/execute/remote_executor.py
powerfulseal/node/inventory.py
powerfulseal/policy/node_scenario.py
powerfulseal/policy/pod_scenario.py
requirements.txt
setup.py
tests/node/test_inventory.py
tests/node/test_node_inventory.py
tests/policy/test_node_scenario.py
tests/policy/test_pod_scenario.py
tests/policy/test_policy_runner.py
tests/policy/test_scenario.py
tox.ini

This pull request adds Python 2.7 compatibility. 
There are no breaking changes for users. However, the testing workflow has been changed to use tox. Additionally, test packages in `requirements.txt` have been moved to `extras_require` as it is the suggested approach to handling test packages in tox.
Resolves #51, resolves #57.

Add Python 2.7 compatibility

---

powerfulseal/cli/__main__.py
setup.py
tests/cli/__init__.py
tests/cli/args.py
tests/cli/test_args.py

Fixes issue where validating a policy file required other, unused arguments.
All changes are backwards-compatible with previous version. Basic integration tests for the CLI and a test case for issue #14 specifically have also been added.
Signed-off-by: Kelvin Zhang <kzhang302@bloomberg.net>

Fix argument parsing with --validate-policy-file (fixes #14)

---

README.md
powerfulseal/cli/__main__.py
powerfulseal/k8s/heapster_client.py
powerfulseal/policy/demo_runner.py
powerfulseal/policy/pod_scenario.py
setup.py
tests/k8s/test_heapster_client.py
tests/policy/test_demo_runner.py

This PR implements demo mode, which is aimed at killing the busiest pods in the cluster in order to inflict the most chaos and demonstrate the effects of PowerfulSeal.
This PR is backwards-compatible with the last minor version.
The algorithm used is that the aggregate of CPU and memory usage per pod (across all of a pod's containers) calculated and pods are sorted descending (CPU, then memory). Then, depending on the aggressiveness (between 1 [weakest] and 5 [strongest] inclusive), the proportion of pods to kill is calculated, then pods are filtered even further based on probability. The result is that the busiest pods (in terms of CPU and memory) are killed with an element of randomness.
The implementation of this depends on [Heapster](https://github.com/kubernetes/heapster), which is …

Implement demo mode

---

powerfulseal/policy/label_runner.py
setup.py
tests/fixtures.py
tests/metriccollectors/test_collector.py
tests/metriccollectors/test_prometheus_collector.py
tests/policy/test_label_runner.py
tests/policy/test_node_scenario.py
tests/policy/test_pod_scenario.py
tests/policy/test_scenario.py

This was initially to see why the prometheus tests started failing, but later scope creeped fixing some warnings from pytests, and a test that wouldn't work on the weekends, but worked fined on a work day.
Also, fixed an issue with sub-second resolution for the label-based usage.

Fix prometheus metrics not passing tests

---

TESTING.md
powerfulseal/clouddrivers/aws_driver.py
tests/clouddrivers/test_aws_driver.py

Description:
Adding a couple tests around aws driver.
- Adds test to check that nodes can be created via public ip address
- Adds test to assert that no nodes are returned if fetching ec2 instances with an invalid ip address
Testing checklist:

Chore - add more test coverage for aws_driver

---

README.md
powerfulseal/cli/__main__.py
powerfulseal/execute/remote_executor.py

With the issue about https://github.com/bloomberg/powerfulseal/issues/88#issuecomment-450300933, I tried using all the validations and found that using password is also a workaround.This can also extend the use of powerfulseal.

add ssh password options

---

powerfulseal/cli/__main__.py
powerfulseal/cli/pscmd.py
powerfulseal/execute/remote_executor.py
powerfulseal/policy/demo_runner.py
powerfulseal/policy/label_runner.py
powerfulseal/policy/pod_scenario.py
powerfulseal/web/server.py
setup.py
tests/fixtures.py

Currently, `sudo docker kill` command is hardcoded.
This PR introduces a new command line argument, `--ssh-kill-command` (still defaulting to `sudo docker kill -s {signal} {container_id}"`) via which the user can customize the docker (or other compatible binary) to be executed.

Allow for kill command customization

---

TESTING.md

Looks like 'pyenv local' example (on recommended installation steps) says 'install' instead of 'local'. Just a small PR fixing this.

Fix 'Pyenv local' example on TESTING.md

---

powerfulseal/cli/__main__.py
powerfulseal/cli/pscmd.py

Fix compatibility between Python 2 and 3 using `six.moves.input()`. Crashed for me today on interactive mode while using Python 2.7. This solution is already used on `pscmd.py ` line 442.

Fix input() compatibility 

---

powerfulseal/policy/policy_runner.py

Just one minor fix for using the safer `safe_load()` instead of `load()` for loading YAML. Some reasoning about this best practice on PyYAML docs [[0](https://pyyaml.org/wiki/PyYAMLDocumentation)] and on this OpenStack Guideline [[1](https://security.openstack.org/guidelines/dg_avoid-dangerous-input-parsing-libraries.html#consequences)].
[[0](https://pyyaml.org/wiki/PyYAMLDocumentation)] https://pyyaml.org/wiki/PyYAMLDocumentation (Loading YAML section)
[[1](https://security.openstack.org/guidelines/dg_avoid-dangerous-input-parsing-libraries.html#consequences)] https://security.openstack.org/guidelines/dg_avoid-dangerous-input-parsing-libraries.html#consequences

Fix YAML load()

---

setup.py

Tracked the dependency to Flask [[0](https://github.com/pallets/flask/issues/2549)] and it has been fixed [[1](http://flask.pocoo.org/docs/1.0/changelog/)] on flask >1.0 (It was related with the JSONIFY_PRETTYPRINT_REGULAR default) so I updated the dependency and seems to solve  #108 . 
On the other side, fixing this generates the following warning:
On Python 2.7,3.4,3.5,3.7:
`.tox/py27/lib/python2.7/site-packages/requests/__init__.py:91
/home/travis/build/dgzlopes/powerfulseal/.tox/py27/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)`
Seems to come from Requests and as reflected on this issue [[2](https://github.com/kennethreitz/requests/issues/5067)] looks like …

Fix #108: Update Flask dependency

---

README.md
powerfulseal/cli/__main__.py
powerfulseal/clouddrivers/__init__.py
powerfulseal/clouddrivers/azure_driver.py
powerfulseal/execute/remote_executor.py
powerfulseal/node/node_inventory.py
setup.py
tests/clouddrivers/test_azure_driver.py

Adds Azure Cloud Driver.
Note: paramiko library changes are required for communication with Azure nodes.  
There is an in-flight PR: https://github.com/paramiko/paramiko/pull/1233.  A user will have to create their own paramiko lib with those changes to be able to use this driver.
Explicit utf-8 encoding was needed to process the strings returned from Azure Docker commands.  This should be ok with all other cloud providers.
New section in overall README for cloud provider specifics added.  This should be filled out more in another PR.
Related issue: https://github.com/bloomberg/powerfulseal/issues/101

Azure Cloud Driver

---

powerfulseal/cli/pscmd.py

PR adds better handling when trying to kill a pod on pending state. This PR closes: #127 
1. Added status check when trying to kill some pod on pending state.
2. Added a color scheme to pods state [0] for easier visualization on
interactive mode.
[0] https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase
Signed-off-by: dgzlopes <danielgonzalezlopes@gmail.com>

Handle killing pods on pending state

---

README.md
powerfulseal/cli/__main__.py
powerfulseal/clouddrivers/__init__.py
powerfulseal/clouddrivers/gcp_driver.py
powerfulseal/k8s/k8s_inventory.py
setup.py
tests/clouddrivers/test_gcp_driver.py

PR adding the GCP cloud driver. This PR closes #123 and is related with #80.
- Implementation of Google Cloud that works with managed (GKE) and custom Kubernetes clusters running on top of Google Cloud Compute.
- Supports zone and regional clusters.
- Supports authentification with Service account and User account. 
- Uses default project/region from gcloud SDK, but supports using a custom configuration file.
This PR also adds testing for the driver, needed dependencies on setup.py, driver arguments for cli, docs in README.md and minor version bump  :smiley:
On the other hand, a little problem closely related to the driver is addressed too! Found that running the ```pods``` command in interactive mode crashed... And seemed that with this little refactor, for gracefully handling missing …

Add GCP driver

---

Makefile
README.md
powerfulseal/cli/__main__.py
powerfulseal/k8s/metrics_server_client.py
powerfulseal/policy/demo_runner.py
tests/k8s/test_metrics_server_client.py

PR handling the transition as discussed. This PR closes #109.
Heapster has reached EOL with Kubernetes 1.13 and metrics-server has become the new standard. This commit fixes the incompatibilities between them, for keeping demo mode working,  like the METRICS_PATH and the use of nanocores instead of milicores.
Also, all past references to Heapster have been modified and the test suite has been adapted.
Signed-off-by: dgzlopes <danielgonzalezlopes@gmail.com>

Transition from Heapster to metrics-server.

---

powerfulseal/clouddrivers/azure_driver.py

Signed-off-by: Mikel Nelson <github@mikelnelson.net>
Azure driver DeprecationWarning #135
Removed unneeded import that is causing deprecation warnings.
Ran tox -r. validated that deprecation warning does not occur.
Closes #135

remove unneeded import

---

.travis.yml
build/Dockerfile

This PR aims to decrease the size of the `powerfulseal` docker image.
This should be dropping it from 631MB to 398MB.
```sh
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
powerfulseal        2.4.0               80db59e06763        1 second ago        398MB
<none>              <none>              b87142b937ba        17 seconds ago      631MB
python              3.7-slim-buster     f96c28b7013f        8 hours ago         179MB
```

Try to decrease docker image size by using a multi-stage build

---

.travis.yml

This commit prepares .travis.yml to enable pushing of packages to
PyPI when tags are pushed to the repository.

Enable pushing of packages to PyPI

---

.travis.yml
setup.py

This installs pandoc and sneakily changes format of `README.md` from Markdown to reStructuredText, so that `PyPI` upload doesn't choke.
- https://github.com/pypa/warehouse/pull/4099#issuecomment-393620919
- https://github.com/pypa/warehouse/issues/4079#issuecomment-392924698

Work around the `text/markdown` support in setup.py

---

.travis.yml

This project's Travis-CI build configuration builds the entire project
more than once, for multiple versions of Python. The deployment
configuration should *not* do this, it should only deploy once for the
latest version of Python available.

Don't run Travis-CI deployment more than once

---

powerfulseal/cli/__main__.py
powerfulseal/k8s/k8s_client.py
setup.py
tests/cli/test_args.py
tests/cli/test_kubeconfig.py

This introduces support for in-cluster config, while maintaining backwards compatible behaviour.
The precedence is as follows:
- `--kubeconfig` flag
- `KUBECONFIG` env var
- `~/.kube/config` for backwards compatibility
- in-cluster
Closes https://github.com/bloomberg/powerfulseal/issues/161

Support in cluster config

---

kubernetes/README.md
kubernetes/powerfulseal.yml
kubernetes/rbac.yml

Signed-off-by: ksatchit <karthik.s@openebs.io>
*Issue number of the reported bug or feature request: #<number>*
fixes #165 
A clear and concise description of the changes you have made.
- Adds example Kubernetes deployment manifests (rbac, powerfulseal) with a brief README to specify run steps. 
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
- Applied the spec on a GKE cluster & observed successful pod chaos
Add any other context about your contribution here.
- The image referred to in the powerfulseal.yml - `bloomberg/powerfulseal:2.5.0` is not present at this point. Open to replacing it with a placeholder OR keep the PR waiting until an …

(example)k8s_manifest: add powerfulseal deployment manifests

---

powerfulseal/cli/__main__.py
powerfulseal/k8s/k8s_client.py
powerfulseal/k8s/k8s_inventory.py
powerfulseal/policy/pod_scenario.py
setup.py
tests/fixtures.py

If set, `--use-pod-delete-instead-of-ssh-kill` will try to use delete pods, instead of sshing and killing the pods via `docker kill`.
Closes https://github.com/bloomberg/powerfulseal/issues/162

License to kill (pods)

---

setup.py

This is when I give up, and stop trying to use the full-featured, markdown `README.md`, and just put a shorter version in `setup.py`.
```
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
PyPI upload failed.
```

Don't use the long markdown description in setup.py

---

.travis.yml
tox.ini

This patch changes the PyPI publishing process:
* Uses `pep517` and `twine` for building package and uploading
* Uses TWINE_PASSWORD (no username) instead of PYPI_USER and PYPI_PASSWORD
* Uses a `tox` environment to run the publishing steps

Improve PyPI publishing process

---

.travis.yml
setup.py

Following https://github.com/bloomberg/powerfulseal/pull/168, it should now be safe to remove the hacks around not being able to use Markdown in the `long_description` field

Revert restructuredtext changes

---

.travis.yml
Makefile
pyproject.toml
setup.py
tox.ini

* Add pyproject.toml so that pep517.build can build the package
* Remove Travis-CI testing for Python 2.7 as setup.py requires Python >= 3
* Add Travis-CI test for Python 3.7 and make 3.7 the base for packaging steps

Add PEP-517 build metadata and other cleanups

---

README.md

PR that adds Datadog metric collector to the README.md highlights.
Signed-off-by: dgzlopes <danielgonzalezlopes@gmail.com>

Add Datadog to highlights

---

powerfulseal/policy/pod_scenario.py

In #164 I forgot to deal with kill metric when using the pod delete, instead of ssh kill.
This fixes that.

Readd the metrics for killing pods, when using api delete and not ssh

---

powerfulseal/cli/__main__.py
powerfulseal/clouddrivers/no_cloud_driver.py

Instead log a big, red message.
Plus a bonus, downgrade an annoying log message to info from error.
Resolves https://github.com/bloomberg/powerfulseal/issues/179

Don't start prometheus http metrics server, if running with Flask debug reloader

---

kubernetes/powerfulseal.yml

*Issue number of the reported bug or feature request: https://github.com/bloomberg/powerfulseal/issues/192
According to the referenced issue, Powerfulseal supports the `--use-pod-delete-instead-of-ssh-kill` argument starting from 2.6.0 version. Thus, the default version in powerfulseal.yml should be at least 2.6.0 since it uses this argument.
I've ran the updated manifests in my test cluster and it works without any error. Also I can confirm that it kill pods according to the defined default policy.
Resolves #192

Update the default powerfulseal version

---

kubernetes/powerfulseal.yml

For some reason 2.6.0 did not report metrics correctly, leaving metrics empty even though the seal was running amok every 30 seconds:
```
sh-4.2# curl http://172.30.215.58:8081/metrics
process_virtual_memory_bytes 374808576.0
process_resident_memory_bytes 129613824.0
process_start_time_seconds 1579022561.59
process_cpu_seconds_total 563.8399999999999
process_open_fds 10.0
process_max_fds 1048576.0
python_info{implementation="CPython",major="3",minor="7",patchlevel="4",version="3.7.4"} 1.0
seal_empty_filter_total 0.0
seal_probability_filter_not_passed_total 0.0
seal_empty_match_total{source="nodes"} 0.0
seal_empty_match_total{source="pods"} 0.0
```
Going to powerfulseal 2.8.0 fixed this issue, so better to have the kubernetes example with this version so others don't have to troubleshoot …

fix prometheus issue on kubernetes

---

powerfulseal/policy/scenario.py
tests/fixtures.py
tests/policy/test_scenario.py

*Issue number of the reported bug or feature request: #204*
When executing a scenario, if there were no matched items or no filtered items, then don't continue executing the scenario.
If there were no matched items, then also ensure that the metrics are updated.
Added unit test to ensure that no further processing of a scenario occurs if there were no matched items.
Added unit test to ensure that no further processing of a scenario occurs if there were no filtered items.
n/a
Resolves https://github.com/bloomberg/powerfulseal/issues/204

Shortcut processing scenario if no matched or filtered items

---

powerfulseal/clouddrivers/azure_driver.py

For large node count azure AKS clusters the azure driver was taking a very long time (10s of minutes) to build the node inventory. Looks like for every group it would re-fetch network interface objects through the azure API for every node.
I added a simple lazy load cache of network interface objects based on resource name (nic resource).
Did development testing against our different AKS cluster sizes to validate no regressions and can now run.

lazy load cache of netinterface objects to reduce azure api thrashing

---

powerfulseal/cli/__main__.py
powerfulseal/policy/policy_runner.py

Signed-off-by: Chris Stanaway <chris.stanaway@here.com>
*Issue number of the reported bug or feature request: #209*
- When policy fails validation, log an error (not info) message.
- When exiting, call `sys.exit()`, not the non-existent `os.exit()`.
Ran seal and provided a malformed policy file.  Got expected error output.
Ran seal without malformed policy and worked as expected.
None.
Fixes #209

Issue #209 fix (#2)

---

.travis.yml
setup.cfg

It initially looked like a good idea, but will be hard to maintain.
It breaks the tag building workflow.

Remove the check for not building the CI based on a git diff

---

docs/2_getting-started.md
docs/policies/http-proxy.md
docs/policies/kubectl.md
docs/schema/index.html
kubernetes/powerfulseal.yml
powerfulseal/cli/pscmd.py
powerfulseal/policy/action_probe_http.py
powerfulseal/policy/ps-schema.yaml
setup.cfg
tests/policy/example_config.yml
tests/policy/test_action_probe_http.py

If you need different proxies for different probes, you're going to like this.

Support per-probe proxies, by default use no proxies, regardless of the ENV

---

.dockerignore
build/Dockerfile
docs/2_getting-started.md
docs/5_setup.md
docs/policies/kubectl.md
docs/schema/index.html
kubernetes/powerfulseal.yml
kubernetes/rbac.yml
powerfulseal/policy/action_kubectl.py
powerfulseal/policy/ps-schema.yaml
setup.cfg
tests/policy/example_config.yml
tests/policy/test_action_kubectl.py

Add support to inject `http{s}_proxy` value for kubectl commands in the schema.
Default to not using the proxies (even if they are in the environement) - this makes it easier to run in pod.

Kubectl proxy, fix docs

---

docs/4_policies.md
docs/6_in-depth.md
docs/schema/index.html
powerfulseal/metriccollectors/collector.py
powerfulseal/metriccollectors/datadog_collector.py
powerfulseal/metriccollectors/prometheus_collector.py
powerfulseal/metriccollectors/stdout_collector.py
powerfulseal/policy/policy_runner.py
powerfulseal/policy/ps-schema.yaml
powerfulseal/policy/scenario.py
setup.cfg
tests/policy/example_config.yml

Resolves https://github.com/bloomberg/powerfulseal/issues/253
It produces metrics like these:
```prometheus
seal_scenario_runs_total{name="wait some",result="success"} 4.0
seal_scenario_runs_total{name="probe some stuff",result="fail"} 3.0
seal_scenario_runs_total{name="delete a random pod in default namespace",result="success"} 3.0
seal_scenario_runs_total{name="Count some pods",result="fail"} 3.0
```

Make exit strategy configurable

---

powerfulseal/k8s/k8s_inventory.py
tests/k8s/test_k8s_inventory.py

https://github.com/bloomberg/powerfulseal/issues/274
I have added an extra if statement when looking for namespaces to match.  It needs to loop through all the namespaces and see if the name regex matches the string I want I am giving from the scenario. 
Currently this will only work with matching any regex at the end of a string. For example, it only matches for "openshift-*" not "*-*" or "*-monitoring", etc... 
I was able to test this locally with a pod kill scenario (see below) I have been working on. 
```
scenarios:
- name: kill one pod in openshift namespace
steps:
- podAction:
matches:
- namespace: "openshift-*"
filters:
- property:
name: "state"
value: "Running"
- randomSample:
size: 1
actions:
- kill:
probability: .7
```

Regex namespace

---

README.md
docs/2_getting-started.md
docs/policies/kubectl.md
kubernetes/powerfulseal.yml
tests/policy/example_config.yml

The store proved difficult to use - people were confused, and you couldn't see the tags available. This changes all the references to point to the regular docker hub.

Update all references to use the regular docker registry, not the store

---

README.md
docs/2_getting-started.md
docs/policies/kubectl.md
docs/policies/pods-and-hosts.md
docs/schema/index.html
kubernetes/powerfulseal.yml
powerfulseal/k8s/k8s_client.py
powerfulseal/policy/action_nodes.py
powerfulseal/policy/action_nodes_pods.py
powerfulseal/policy/action_pods.py
powerfulseal/policy/ps-schema.yaml
powerfulseal/policy/scenario.py
setup.cfg
tests/policy/example_config.yml

Often, you want to stop a host that runs a particular pod. Right now, you need to do some gymnastics to achieve that.
With `stopHost`, you can select all the pods you like, and stop all the hosts that are involved in running that set.
This will restart the nodes at the end of the scenario
```yaml
scenarios:
- name: Hello chaos!
steps:
- podAction:
matches:
- namespace: something
filters:
- randomSample:
size: 1
actions:
- stopHost:
autoRestart: true
- wait:
seconds: 30
```

Add a new podAction: stopHost

---

README.md
docs/2_getting-started.md
docs/4_policies.md
docs/policies/kubectl.md
kubernetes/powerfulseal.yml
powerfulseal/policy/action_nodes_pods.py
setup.cfg
tests/policy/example_config.yml
tests/policy/test_action_nodes.py
tests/policy/test_action_pods.py

Currently, it's a little bit too easy to shoot yourself in the foot by killing the pod or the host that PowerfulSeal is running on.
This prevents it from happening, as long as you provide the `HOST_IP` and `POD_NAME` environment variables.

Don't self destruct

---

.travis.yml
Makefile
build/Dockerfile

Resolves #288 
1. ARM64 architecture has been added to .travis.yml file.
2. Installed libffi-dev and libssl-dev in the RUN clause of the Dockerfile for ARM64. libffi-dev and libssl-dev are required for installing pynacl package in ARM64.
3. Added a check in the RUN clause of the Dockerfile, for downloading kubectl binary according to the
host platform.
Signed-off-by: odidev <odidev@puresoftware.com>

Added ARM64 support for generating ARM64 docker containers and added ARM64 support to Travis-CI

---

README.md

This commit adds a pointer to Kraken - chaos and resiliency tool
which consumes PowerfulSeal under the hood and maintained by
OpenShift Performance and Scale Team. Thanks to the PowerfulSeal
community for the amazing tool.
Signed-Off-By: Naga Ravi Chaitanya Elluri <nelluri@redhat.com>

Mention Kraken in the docs

---

powerfulseal/policy/action_pods.py
setup.cfg

Currently, setting `POD_NAME` and `HOST_IP` to the correct values will prevent PowerfulSeal from killing its own pod and host.
Unfortunately, that was never added to the kill host feature of pod host, so PowerfulSeal was happily self-destructing when using that. This PR fixes that.

Fix stop host action

---

powerfulseal/policy/action_alertmanager.py
powerfulseal/policy/ps-schema.yaml
powerfulseal/policy/scenario.py
tests/fixtures.py
tests/policy/test_action_alertmanager.py

```
steps:
- alertManagerAction:
targets:
- url: http://<alert_manager_1_url>:9093/api/v2
- url: http://<alert_manager_2_url>:9093/api/v2
actions:
- mute:
```
```
actions:
- mute:
autoUnmute:  false
```

Add alertmanager action to provide ability to mute alerts during chaos engineering

---

powerfulseal/policy/action_probe_http.py
tests/policy/test_action_probe_http.py

Closes #342.
This implements handling of the probeHTTP `code` field, which allows the user to specify the expected return code of an HTTP probe. Previously, setting this didn't work, unless the code returned was a non-4xx or 5xx code.

Honor probeHTTP code field

---

powerfulseal/k8s/k8s_client.py
setup.cfg

The addition of [ApiextensionsV1beta1Api](https://github.com/powerfulseal/powerfulseal/commit/c51c567cc20f811bdfc45ac174feec0e9782f799)broke the autonomous pod scenarios for OpenShift 4.9. With setting the kuberenetes api to ApiextensionsV1Api it should work for all versions. 
Note: Updated the version of kubernetes as well. Definitely does not have to be added in this PR but think it should be updated to a more recent version soon

Api v1 broke 4.9 OpenShift
