powerfulseal/powerfulseal

- README.md
> Added an extra answer to FAQ

- README.md
> Improve grammar in README.

- setup.py
> Add url to setup.py

- powerfulseal/cli/__main__.py
- setup.py
> Account for the change to make main function testable

- setup.py
Closes https://github.com/bloomberg/powerfulseal/issues/2
> Prepare for PyPi upload

- README.md
> Fix: missing file

- powerfulseal/cli/pscmd.py
Closes https://github.com/bloomberg/powerfulseal/issues/26
> Remove duplication between `complete_` operations

- powerfulseal/k8s/k8s_inventory.py
> Don't barf on evicted pods with no containers

- .travis.yml
- powerfulseal/clouddrivers/open_stack_driver.py
- setup.py
Like @taliaga noticed, `openstacksdk` needed an update.
Closes https://github.com/bloomberg/powerfulseal/issues/36
> Fix OpenStack driver, update to 0.10.0

- setup.py
> Bump patch version to 1.1.1

- powerfulseal/cli/__main__.py
- powerfulseal/clouddrivers/__init__.py
- powerfulseal/clouddrivers/aws_driver.py
- powerfulseal/execute/remote_executor.py
- setup.py
- tests/clouddrivers/test_aws_driver.py
Signed-off-by: Oleksandr Stepanov <alexandrst88@gmail.com>
- Added AWS cloud provider
- Added cmd option to choose path to SSH private key
If you will approve code, and it's logic and etc, I would add some tests after it. Thanks.
> AWS support + ssh private key path

- powerfulseal/policy/pod_scenario.py
- setup.py
- tests/policy/test_pod_scenario.py
Will this blend? https://github.com/bloomberg/powerfulseal/pull/52
> read probability instead of killing anyway

- Makefile
- README.md
- powerfulseal/cli/__main__.py
- powerfulseal/cli/pscmd.py
- powerfulseal/execute/remote_executor.py
- setup.py
- tests/cli/test_args.py
> Minor changes to make the Seal work with minikube out of the box

- setup.py
> Bump to version 2.0.1

- powerfulseal/metriccollectors/prometheus_collector.py
- tests/metriccollectors/test_prometheus_collector.py
Fixes https://github.com/bloomberg/powerfulseal/issues/93
> Fix prometheus metrics collector

- README.md
- powerfulseal/cli/__main__.py
It took me some digging to figure out what kind of inventory file Powerful Seal will take, so I've surfaced that a bit better both in the README and in the CLI documentation
> Improve documentation for inventory files

- powerfulseal/cli/__main__.py
- powerfulseal/cli/pscmd.py
Signed-off-by: Mikel Nelson <github@mikelnelson.net>
highjack system exception GeneratorExit for use.
Resolves: #110
> Add exit command

- powerfulseal/cli/__main__.py
- powerfulseal/version.py
This PR adds version tracking and display using setup.py version as a single source of truth. 
Resolves issue #100.
Deleted other PR like this one because my sign was doing weird things! I hope it's all fine now.
> Add version tracking and display

- README.md
This attempts to declutter the README, which has grown organically a fair bit..
> Declutter the README a little bit

- README.md
- powerfulseal/policy/policy_runner.py
- powerfulseal/policy/ps-schema.json
- setup.py
- tests/policy/example_config2.yml
- tests/policy/test_policy_runner.py
In `autonomous` mode, if `config.loopsNumber` is specified, run that many times and exit.
Closes #90
> Implement `config.loopsNumber` to allow running N times and exiting

- setup.py
For a new release `2.4.1` containing all the patches.
> Patch version bump

- build/Dockerfile
Closes https://github.com/bloomberg/powerfulseal/issues/154
> Expliclitly build an sdist and then install that

- TESTING.md
Update docs with the current Python versions used in Tox.
> Update Python versions on TESTING.md

- powerfulseal/web/server.py
Signed-Off-By: Pavel Nagornyuk <gp4vel@gmail.com>
*Issue number of the reported bug or feature request:* #178 
Allow powerfulseal UI to work correctly behind a proxy
You can find more information here: https://werkzeug.palletsprojects.com/en/0.15.x/middleware/proxy_fix/#module-werkzeug.middleware.proxy_fix
> Allow powerfulseal UI to work correctly behind a proxy

- powerfulseal/policy/policy_runner.py
Resolves https://github.com/bloomberg/powerfulseal/issues/180
> Fix loop number default - if not set, loop indefinitely 

- kubernetes/powerfulseal.yml
Signed-off-by: mhamdi semah <mhamdi.semah@gmail.com>
*Issue number of the reported bug or feature request: #186*
> correct the image url

- README.md
Small PR fixing menu indentation and hierarchy. Aligns PowerfulSeal logo too :) 
> Improve README.md style

- powerfulseal/policy/label_runner.py
- tests/policy/test_label_runner.py
Signed-off-by: Jérôme PENE-KUSU <jpenekusu@gmail.com>
*Issue number of the reported bug or feature request: #210*
I have updated the module label_runner.py to take into account the argument use-pod-delete-instead-of-ssh-kill (delete pods through k8s API instead of SSHing into the cluster node).
I made two tests:
- One with the argument use-pod-delete-instead-of-ssh-kill set for non regression
- An other one with the argument not set to validate the fixing
I will provide chaos engineering services to many teams, each having their own namespaces.
I want to use the label mode to allow each team to manage their chaos policy rules, by opposite to the autonomous mode where policy rules are centrally managed by powerfulseal. …
> This commit fixes #210

- powerfulseal/cli/pscmd.py
- powerfulseal/execute/kubernetes_executor.py
- powerfulseal/k8s/k8s_inventory.py
Resolves https://github.com/bloomberg/powerfulseal/issues/23
> Print a message when no hosts match in interactive mode

- powerfulseal/cli/__main__.py
- powerfulseal/k8s/k8s_inventory.py
Resolves https://github.com/bloomberg/powerfulseal/issues/214
> Support using a comma-separated list of namespaces for the label mode

- docs/index.md
> Fix Getting Started url

- setup.cfg
Resolves https://github.com/bloomberg/powerfulseal/issues/244
> Update setup.cfg to 2.9.1

- docs/cloud-provider-requirements.md
- powerfulseal/clouddrivers/gcp_driver.py
- Disable cache discovery
- Change docs example
> Update GCP driver

- README.md
- docs/2_getting-started.md
- docs/policies/kubectl.md
- kubernetes/powerfulseal.yml
- powerfulseal/k8s/k8s_client.py
- powerfulseal/policy/policy_runner.py
- setup.cfg
- tests/policy/example_config.yml
- tests/policy/test_policy_runner.py
Currently the loop waits between scenarios instead of between runs as supposed
*Issue number of the reported bug or feature request: #<number>*
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.
> Policy-runner: wait between runs rather than between scenarios

- README.md
- docs/2_getting-started.md
- docs/4_policies.md
- docs/policies/kubectl.md
- kubernetes/powerfulseal.yml
- setup.cfg
- tests/policy/example_config.yml
> Version 3.0.0 everyone!

- .travis.yml
*Issue number of the reported bug or feature request: #<number>*
A clear and concise description of the changes you have made.
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
Add any other context about your contribution here.
> Fix the arm64 condition for pip publishing

- README.md
- docs/1_index.md
- docs/2_getting-started.md
- docs/4_policies.md
- docs/5_setup.md
- docs/6_in-depth.md
- docs/7_faq.md
- docs/8_contribute.md
- docs/_config.yml
- docs/modes/autonomous.md
- docs/policies/kubectl.md
- kubernetes/powerfulseal.yml
- powerfulseal/cli/__main__.py
- powerfulseal/policy/ps-schema.yaml
- setup.cfg
- tests/policy/example_config.yml
Obvious fixes to accommodate the org name change.
> Org name change fixes (part 1)

- README.md
- docs/2_getting-started.md
- docs/policies/kubectl.md
- kubernetes/powerfulseal.yml
- powerfulseal/policy/policy_runner.py
- setup.cfg
- tests/policy/example_config.yml
- tests/policy/test_policy_runner.py
Otherwise it makes demos awkward!
> When running a number of loops, don't sleep on the last one

- powerfulseal/policy/action_clone.py
#307 #hacktoberfest-accepted <3
> Avoid requesting SecurityContext for toxicproxy
